"""initial schema

Revision ID: d86f2d60287e
Revises: 
Create Date: 2026-06-02 17:29:19.604554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86f2d60287e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrivals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('actual_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_via', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arrivals_route_stop_at', 'arrivals', ['route_id', 'stop_id', 'actual_arrival_at'], unique=False)
    op.create_index('ix_arrivals_vehicle_at', 'arrivals', ['vehicle_id', 'actual_arrival_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('predicted_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_stop_route_captured', 'predictions', ['stop_id', 'route_id', 'captured_at'], unique=False)
    op.create_index('ix_predictions_vehicle_captured', 'predictions', ['vehicle_id', 'captured_at'], unique=False)
    op.create_table('reliability_stats',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('dow', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('on_time_pct', sa.Float(), nullable=False),
    sa.Column('mean_delay_s', sa.Float(), nullable=False),
    sa.Column('p50_delay_s', sa.Float(), nullable=False),
    sa.Column('p90_delay_s', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'stop_id', 'dow', 'hour')
    )
    op.create_index('ix_reliability_lookup', 'reliability_stats', ['route_id', 'stop_id', 'dow', 'hour'], unique=False)
    op.create_table('route_stops',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'stop_id', 'sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_stops')
    op.drop_index('ix_reliability_lookup', table_name='reliability_stats')
    op.drop_table('reliability_stats')
    op.drop_index('ix_predictions_vehicle_captured', table_name='predictions')
    op.drop_index('ix_predictions_stop_route_captured', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_arrivals_vehicle_at', table_name='arrivals')
    op.drop_index('ix_arrivals_route_stop_at', table_name='arrivals')
    op.drop_table('arrivals')
    op.drop_table('stops')
    op.drop_table('routes')
    op.drop_table('parse_errors')
    # ### end Alembic commands ###
